/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * e.g. 2014-06-29
 */
export type Iso8601 = string;

export interface SolidverseResumeSchema {
  /**
   * link to the version of the schema that can validate the resume
   */
  $schema?: string;
  personalInfo?: {
    /**
     * e.g. 2014-06-29
     */
    image?: string;
    name?: string;
    /**
     * e.g. Web Developer
     */
    title?: string;
    /**
     * e.g. thomas@gmail.com
     */
    email?: string;
    /**
     * Phone numbers are stored as strings so use any format you like, e.g. 712-117-2923
     */
    phone?: string;
    /**
     * URL (as per RFC 3986) to your website, e.g. personal homepage
     */
    url?: string;
    /**
     * Write a short 2-3 sentence biography about yourself
     */
    summary?: string;
    location?: {
      /**
       * eg. 1234 Glücklichkeit Straße
       */
      address?: string;
      postalCode?: string;
      city?: string;
      /**
       * Name of country.
       */
      country?: string;
      /**
       * The general region where you live. Can be a US state, or a province, for instance.
       */
      region?: string;
      [k: string]: unknown;
    };
    [k: string]: unknown;
  };
  /**
   * Specify any number of social networks that you participate in
   */
  profiles?: {
    /**
     * e.g. Facebook or Twitter
     */
    network?: string;
    /**
     * e.g. neutralthoughts
     */
    username?: string;
    /**
     * e.g. http://twitter.example.com/neutralthoughts
     */
    url?: string;
    [k: string]: unknown;
  }[];
  /**
   * Work experience. Should be from oldest to most recent.
   */
  work?: {
    /**
     * e.g. Facebook
     */
    name?: string;
    /**
     * e.g. Menlo Park, CA
     */
    location?: string;
    /**
     * e.g. Software Engineer
     */
    position?: string;
    /**
     * e.g. http://facebook.example.com
     */
    url?: string;
    /**
     * e.g. 2014-06-29
     */
    startDate?: string;
    /**
     * e.g. 2014-06-29
     */
    endDate?: string;
    /**
     * Give an overview of your responsibilities and experiences at the company.
     */
    summary?: string;
    [k: string]: unknown;
  }[];
  /**
   * List your education.
   */
  education?: {
    /**
     * e.g. Massachusetts Institute of Technology
     */
    institution?: string;
    /**
     * e.g. http://facebook.example.com
     */
    url?: string;
    /**
     * e.g. Arts
     */
    area?: string;
    /**
     * e.g. Bachelor
     */
    studyType?: string;
    startDate?: Iso8601;
    endDate?: Iso8601;
    /**
     * grade point average, e.g. 3.67/4.0
     */
    score?: string;
    /**
     * List notable courses/subjects
     */
    courses?: string[];
    [k: string]: unknown;
  }[];
  /**
   * Specify any awards you have received throughout your professional career
   */
  awards?: {
    /**
     * e.g. One of the 100 greatest minds of the century
     */
    title?: string;
    /**
     * e.g. 2014-06-29
     */
    date?: string;
    /**
     * e.g. Time Magazine
     */
    awarder?: string;
    /**
     * e.g. Received for my work with Quantum Physics
     */
    summary?: string;
    [k: string]: unknown;
  }[];
  /**
   * Specify any certificates you have received throughout your professional career
   */
  certificates?: {
    /**
     * e.g. Certified Kubernetes Administrator
     */
    name?: string;
    /**
     * e.g. 1989-06-12
     */
    date?: string;
    /**
     * e.g. http://example.com
     */
    url?: string;
    /**
     * e.g. CNCF
     */
    issuer?: string;
    [k: string]: unknown;
  }[];
  /**
   * Specify your publications through your career
   */
  publications?: {
    /**
     * e.g. The World Wide Web
     */
    name?: string;
    /**
     * e.g. IEEE, Computer Magazine
     */
    publisher?: string;
    /**
     * e.g. 2014-06-29
     */
    releaseDate?: string;
    /**
     * e.g. http://www.computer.org.example.com/csdl/mags/co/1996/10/rx069-abs.html
     */
    url?: string;
    /**
     * Short summary of publication. e.g. Discussion of the World Wide Web, HTTP, HTML.
     */
    summary?: string;
    [k: string]: unknown;
  }[];
  /**
   * List out your professional skill-set
   */
  skills?: {
    /**
     * e.g. Web Development
     */
    name?: string;
    /**
     * e.g. Master or Novice
     */
    level?: string;
    /**
     * Level of skill in a number from 1 to 5
     */
    levelNumber?: number;
    /**
     * List some keywords pertaining to this skill
     */
    keywords?: string[];
    [k: string]: unknown;
  }[];
  /**
   * List any other languages you speak
   */
  languages?: {
    /**
     * e.g. English, Spanish
     */
    language?: string;
    /**
     * e.g. Fluent, Beginner
     */
    fluency?: string;
    [k: string]: unknown;
  }[];
  interests?: {
    /**
     * e.g. Philosophy
     */
    name?: string;
    keywords?: string[];
    [k: string]: unknown;
  }[];
  /**
   * Volunteering experience. Should be from oldest to most recent.
   */
  volunteer?: {
    /**
     * e.g. Facebook
     */
    organization?: string;
    /**
     * e.g. Software Engineer
     */
    position?: string;
    /**
     * e.g. http://facebook.example.com
     */
    url?: string;
    /**
     * e.g. 2014-06-29
     */
    startDate?: string;
    /**
     * e.g. 2014-06-29
     */
    endDate?: string;
    /**
     * Give an overview of your responsibilities at the company
     */
    summary?: string;
    [k: string]: unknown;
  }[];
  /**
   * Specify career projects
   */
  projects?: {
    images?: Iso8601[];
    /**
     * e.g. The World Wide Web
     */
    name?: string;
    /**
     * Short summary of project. e.g. Collated works of 2017.
     */
    description?: string;
    /**
     * e.g. 2014-06-29
     */
    startDate?: string;
    /**
     * e.g. 2014-06-29
     */
    endDate?: string;
    /**
     * e.g. http://www.computer.org/csdl/mags/co/1996/10/rx069-abs.html
     */
    url?: string;
    /**
     * Give a summary of this project
     */
    summary?: string;
    /**
     * Specify special elements involved
     */
    keywords?: string[];
    [k: string]: unknown;
  }[];
  /**
   * Specify references
   */
  references?: {
    image?: string;
    [k: string]: unknown;
  }[];
  /**
   * Custom Sections
   */
  custom?: {
    /**
     * Specify MDI icon from https://pictogrammers.github.io/@mdi/font/2.0.46/
     */
    icon?: string;
    /**
     * Title of custom section
     */
    title?: string;
    /**
     * Sub title of custom section
     */
    subtitle?: string;
    /**
     * e.g. 2014-06-29
     */
    startDate?: string;
    /**
     * e.g. 2014-06-29
     */
    endDate?: string;
    /**
     * e.g. http://www.computer.org/csdl/mags/co/1996/10/rx069-abs.html
     */
    url?: string;
    /**
     * e.g. Master or Novice
     */
    level?: string;
    /**
     * Level of skill in a number from 1 to 5
     */
    levelNumber?: number;
    /**
     * Content of custom section
     */
    content?: string;
    /**
     * Specify special elements involved
     */
    keywords?: string[];
    [k: string]: unknown;
  }[];
  /**
   * The schema version and any other tooling configuration lives here
   */
  meta?: {
    /**
     * URL (as per RFC 3986) to latest version of this document
     */
    canonical?: string;
    /**
     * A version field which follows semver - e.g. v1.0.0
     */
    version?: string;
    /**
     * Using ISO 8601 with YYYY-MM-DDThh:mm:ss
     */
    lastModified?: string;
    [k: string]: unknown;
  };
}
